<#
.SYNOPSIS
    Generate the winget installer manifest for a built MSI.

.DESCRIPTION
    A winget installer manifest needs two values that change with every build:
    the installer's SHA256 and the MSI's ProductCode. Copying either by hand at
    release time is how a manifest ends up pointing at the wrong binary, so the
    release workflow runs this instead.

    Run from the repository root, after `cargo tauri build`.

.PARAMETER BundleDir
    Where the Tauri bundler put its output.

.PARAMETER Tag
    The git tag the release was published under, used verbatim in the download
    URL. The tag and the version are *different strings* — the tag is
    `tsudev-cwico-v26.8.19` and the version is `26.8.1901` — and treating one
    as the other produces a URL that 404s. Defaults to the tag this version
    would be published under.

.PARAMETER Repository
    `owner/name`, used to build the release download URL.

.PARAMETER OutFile
    Where to write the manifest.

.EXAMPLE
    ./tools/winget-manifest.ps1 -Tag tsudev-cwico-v26.8.19
#>
[CmdletBinding()]
param(
    [string]$BundleDir = "app/src-tauri/target/release/bundle",
    [string]$Tag = "",
    [string]$Repository = "tsudev-tsudev/tsudev-cwico",
    [string]$OutFile = "winget-installer-manifest.yaml"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $BundleDir)) {
    # A cargo workspace puts the bundle under the workspace target dir.
    $BundleDir = "target/release/bundle"
}
if (-not (Test-Path $BundleDir)) {
    throw "no bundle directory found; run `cargo tauri build` first"
}

$msi = Get-ChildItem -Path $BundleDir -Recurse -Filter *.msi | Select-Object -First 1
if (-not $msi) { throw "no MSI in $BundleDir" }

$sha = (Get-FileHash $msi.FullName -Algorithm SHA256).Hash

# ProductCode lives in the MSI's Property table, reachable through the Windows
# Installer COM API. Late binding keeps this working without a typelib.
$installer = New-Object -ComObject WindowsInstaller.Installer
$db = $installer.GetType().InvokeMember(
    "OpenDatabase", "InvokeMethod", $null, $installer, @($msi.FullName, 0))
$view = $db.GetType().InvokeMember(
    "OpenView", "InvokeMethod", $null, $db,
    @("SELECT Value FROM Property WHERE Property = 'ProductCode'"))
$view.GetType().InvokeMember("Execute", "InvokeMethod", $null, $view, $null)
$record = $view.GetType().InvokeMember("Fetch", "InvokeMethod", $null, $view, $null)
if (-not $record) { throw "the MSI has no ProductCode property" }
$productCode = $record.GetType().InvokeMember("StringData", "GetProperty", $null, $record, 1)

# The version always comes from the manifests. An earlier revision derived it
# from `github.ref_name`, which produced `.../download/v26.8.1901/...` — the
# version where the tag belongs, and a URL that 404s.
$conf = Get-Content "app/src-tauri/tauri.conf.json" -Raw | ConvertFrom-Json
$Version = $conf.version

# The tag goes into the URL verbatim, because that is what the asset path
# contains. On a manual run `github.ref_name` is a branch name, so derive the
# tag this version would be published under instead.
if (-not $Tag -or $Tag -notmatch '^tsudev-cwico-v') {
    if ($Tag) { Write-Host "ref '$Tag' is not a release tag; deriving it from the version" }
    $Tag = (python3 tools/version.py to-name $Version).Trim()
}

$url = "https://github.com/$Repository/releases/download/$Tag/$($msi.Name)"
$today = Get-Date -Format 'yyyy-MM-dd'

$lines = @(
    '# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json'
    '# Generated by tools/winget-manifest.ps1 — do not edit by hand.'
    'PackageIdentifier: tsudev.cwico'
    "PackageVersion: $Version"
    'MinimumOSVersion: 10.0.19041.0'
    'InstallerType: wix'
    'Scope: machine'
    'InstallModes:'
    '  - interactive'
    '  - silent'
    '  - silentWithProgress'
    'UpgradeBehavior: install'
    '# The app asks for elevation itself when the user chooses to remove'
    '# something; the installer needs it to write to Program Files.'
    'ElevationRequirement: elevatesSelf'
    "ReleaseDate: $today"
    'Installers:'
    '  - Architecture: x64'
    "    InstallerUrl: $url"
    "    InstallerSha256: $sha"
    "    ProductCode: '$productCode'"
    'ManifestType: installer'
    'ManifestVersion: 1.6.0'
)

$lines -join "`n" | Set-Content -Path $OutFile -Encoding utf8
Write-Host "wrote $OutFile"
Write-Host "  tag         $Tag"
Write-Host "  installer   $($msi.Name)"
Write-Host "  sha256      $sha"
Write-Host "  productCode $productCode"
