<#
.SYNOPSIS
    Generate the winget installer manifest for a built MSI.

.DESCRIPTION
    A winget installer manifest needs two values that change with every build:
    the installer's SHA256 and the MSI's ProductCode. Copying either by hand at
    release time is how a manifest ends up pointing at the wrong binary, so the
    release workflow runs this instead.

    Run from the repository root, after `cargo tauri build`.

.PARAMETER BundleDir
    Where the Tauri bundler put its output.

.PARAMETER Version
    Package version, without a leading `v`. Defaults to the version in
    tauri.conf.json.

.PARAMETER Repository
    `owner/name`, used to build the release download URL.

.PARAMETER OutFile
    Where to write the manifest.

.EXAMPLE
    ./tools/winget-manifest.ps1 -Repository tsudev-tsudev/tsudev-cwico
#>
[CmdletBinding()]
param(
    [string]$BundleDir = "app/src-tauri/target/release/bundle",
    [string]$Version = "",
    [string]$Repository = "tsudev-tsudev/tsudev-cwico",
    [string]$OutFile = "winget-installer-manifest.yaml"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $BundleDir)) {
    # A cargo workspace puts the bundle under the workspace target dir.
    $BundleDir = "target/release/bundle"
}
if (-not (Test-Path $BundleDir)) {
    throw "no bundle directory found; run `cargo tauri build` first"
}

$msi = Get-ChildItem -Path $BundleDir -Recurse -Filter *.msi | Select-Object -First 1
if (-not $msi) { throw "no MSI in $BundleDir" }

$sha = (Get-FileHash $msi.FullName -Algorithm SHA256).Hash

# ProductCode lives in the MSI's Property table, reachable through the Windows
# Installer COM API. Late binding keeps this working without a typelib.
$installer = New-Object -ComObject WindowsInstaller.Installer
$db = $installer.GetType().InvokeMember(
    "OpenDatabase", "InvokeMethod", $null, $installer, @($msi.FullName, 0))
$view = $db.GetType().InvokeMember(
    "OpenView", "InvokeMethod", $null, $db,
    @("SELECT Value FROM Property WHERE Property = 'ProductCode'"))
$view.GetType().InvokeMember("Execute", "InvokeMethod", $null, $view, $null)
$record = $view.GetType().InvokeMember("Fetch", "InvokeMethod", $null, $view, $null)
if (-not $record) { throw "the MSI has no ProductCode property" }
$productCode = $record.GetType().InvokeMember("StringData", "GetProperty", $null, $record, 1)

# `github.ref_name` is the tag on a tag push but the *branch* name on a manual
# run, so an emptiness check is not enough — "main" is a non-empty value that
# is not a version. Fall back unless it actually looks like one.
if ($Version -notmatch '^v?\d+\.\d+') {
    if ($Version) {
        Write-Host "ref '$Version' is not a version; reading tauri.conf.json instead"
    }
    $conf = Get-Content "app/src-tauri/tauri.conf.json" -Raw | ConvertFrom-Json
    $Version = $conf.version
}
$Version = $Version -replace '^v', ''

$url = "https://github.com/$Repository/releases/download/v$Version/$($msi.Name)"
$today = Get-Date -Format 'yyyy-MM-dd'

$lines = @(
    '# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json'
    '# Generated by tools/winget-manifest.ps1 — do not edit by hand.'
    'PackageIdentifier: tsudev.cwico'
    "PackageVersion: $Version"
    'MinimumOSVersion: 10.0.19041.0'
    'InstallerType: wix'
    'Scope: machine'
    'InstallModes:'
    '  - interactive'
    '  - silent'
    '  - silentWithProgress'
    'UpgradeBehavior: install'
    '# The app asks for elevation itself when the user chooses to remove'
    '# something; the installer needs it to write to Program Files.'
    'ElevationRequirement: elevatesSelf'
    "ReleaseDate: $today"
    'Installers:'
    '  - Architecture: x64'
    "    InstallerUrl: $url"
    "    InstallerSha256: $sha"
    "    ProductCode: '$productCode'"
    'ManifestType: installer'
    'ManifestVersion: 1.6.0'
)

$lines -join "`n" | Set-Content -Path $OutFile -Encoding utf8
Write-Host "wrote $OutFile"
Write-Host "  installer   $($msi.Name)"
Write-Host "  sha256      $sha"
Write-Host "  productCode $productCode"
